Add redux toolkit to bookstore
shahzaman900/Bookstore pull request #2
Opened 2023-08-24 11:39 UTC by sheezu900

### Add redux toolkit to bookstore

1. Install the redux toolkit
2. create store 
3. create booksSlice file
4. create categorySlice file 
5. add functionality

2023-08-24 12:21 UTC, OyePriscilla requested changes
Hi @sheezu900 👍 👍, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Added Redux Toolkit ✔️
Created a directory that will contained all your Redux logic ✔️ 

## Required Changes ♻️

- [x] I coudn't access your app because of the error screenshot below 👇 , kindly import `store.js` correctly in `index.js` file. 
`import Store from './redux/store';
`
<img width="858" alt="Untitled" src="https://github.com/sheezu900/Bookstore/assets/103386183/8b097505-8b7a-432d-9efe-628630f99374">



## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-24 12:21 UTC, OyePriscilla commented on src/redux/books/booksSlice.js
> +    removeBook: (state) => state,
- [ ] The logic for adding and removing book(s) is missing from your implementation, kindly reference this [tutorial](https://medium.com/@ralph1786/adding-and-removing-items-from-redux-store-6d1303ed32c6). ℹ️ Every time object is added or remove via the reducer, twoactions are performed to update the array either to add or remove. 🙏 

<img width="643" alt="Untitled" src="https://github.com/sheezu900/Bookstore/assets/103386183/c43f9645-3507-4cc4-8036-a9093959f90e">

2023-08-24 12:21 UTC, OyePriscilla commented on src/redux/books/booksSlice.js
> +  initialState: [],
- [ ] Kindly take not that for proper identification, the name is not supposed to be empty. ℹ️ Kindly give it a descriptive name, maybe `books`.

2023-08-24 12:21 UTC, OyePriscilla commented on src/redux/store.js
> +});
Kindly import the two reducers you implemented in the redux directory for them to be accesible by the store; don't forget to configure them into the reducer.

```Example
import { configureStore } from "@reduxjs/toolkit"
import booksReducer from "./books/booksSlice"
import categoriesReducer from "./categories/categoriesSlice"

const store = configureStore({
  reducer: { books: booksReducer, categories: categoryReducer },
})
;
```

The code snippet is just an example.

2023-08-24 12:21 UTC, OyePriscilla commented on src/redux/categories/categoriesSlice.js
> +});
- [ ] Kindly take not that for proper identification, the name is not supposed to be empty. ℹ️ Kindly give it a descriptive name, maybe `categories`. 

- [ ] The logic for the category state is missing as well, kindy implement it. 👍 

```example
reducers: {
    checkStatus: (state, action) => {
      state.categories =
        action.payload === "Under construction"
          ? "Under construction"
          : state.categories
    },
  },
```
```

![Uploading Untitled.png…]()

2023-08-24 12:21 UTC, OyePriscilla commented on src/redux/categories/categoriesSlice.js
> +});
- [ ] Kindly take not that for proper identification, the name is not supposed to be empty. ℹ️ Kindly give it a descriptive name, maybe `categories`. 

- [ ] The logic for the category state is missing as well, kindy implement it. 👍 

```example
reducers: {
    checkStatus: (state, action) => {
      state.categories =
        action.payload === "Under construction"
          ? "Under construction"
          : state.categories
    },
  },
```
```

<img width="643" alt="Untitled" src="https://github.com/sheezu900/Bookstore/assets/103386183/c3d55a48-d21f-40a6-9bd5-24891c247ce7">

2023-08-25 07:23 UTC, divinecharlotte approved these changes
# Hello @sheezu900     😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say  👍🏻 ✅ 
### To Highlight 💯


- Good implementation of the required changes👍 
- well-organized structure✔ 👍
 




## Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers, and Happy coding!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-25 07:25 UTC, merged